# Netlify configuration for DentalHub

[build]
  # Command to build your site
  command = "npm run build"
  # Directory to publish (Vite default is "dist")
  publish = "dist"

# Functions configuration
[functions]
  # Directory where your Netlify functions are located
  directory = "netlify/functions"
  # Use esbuild for better performance
  node_bundler = "esbuild"
  # Increase timeout for functions that may take longer (like AI operations)
  timeout = 30
  # Include all necessary files for functions
  included_files = ["netlify/functions/**/*.js"]

# Environment variable configuration
[build.environment]
  # These are build-time environment variables
  # Runtime environment variables should be set in the Netlify UI
  NODE_VERSION = "18"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true  # Make sure this redirect is always applied

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://api.deepseek.com https://*.netlify.app https://www.google-analytics.com;"

# Performance optimization for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"