# Netlify configuration for DentalHub - Production Ready Version

[build]
  # Command to build your site
  command = "npm run build"
  # Directory to publish (Vite default is "dist")
  publish = "dist"
  # Ignore certain files/directories during build
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF netlify/ src/"

# Functions configuration
[functions]
  # Directory where your Netlify functions are located
  directory = "netlify/functions"
  # Use esbuild for better performance
  node_bundler = "esbuild"
  # Increase timeout for functions that may take longer (like AI operations)
  [functions.timeout]
    external_node_modules = []
    time = 30
  # Include all necessary files for functions
  included_files = ["netlify/functions/**/*.js"]
  
  # External node modules that should be included
  
  # Individual function configurations
  [functions.health-check]
    # Health check should have a shorter timeout
    [functions.health-check.timeout]
      external_node_modules = []
      time = 10

# Environment variable configuration
[dev]
  # Prevent Netlify Dev from automatically running a framework start command (like 'npm run dev'),
  # as our start-dev.cjs script handles starting Vite on the targetPort.
  # Using ':' as a no-op command.
  command = "timeout /t -1" # Keep alive command for Windows

  # framework = "#auto" # This can be left commented out or removed if 'command' is specified.
  
  # Port for Netlify Dev's own server.
  # We primarily care about it starting the functions server.
  port = 8888

  # Port for the Netlify functions server
  functionsPort = 9999

  # Port for your application server (Vite)
  # This will be the port Vite runs on. start-dev.cjs may override this with a flag if it finds a different free port.
  targetPort = 5173

  # Auto-launch browser - set to false as we'll manage this
  autoLaunch = false

[build.environment]
  # These are build-time environment variables
  # Runtime environment variables should be set in the Netlify UI
  NODE_VERSION = "18"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true  # Make sure this redirect is always applied

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.supabase.co https://api.deepseek.com https://*.netlify.app https://www.google-analytics.com https://dentalhub.netlify.app https://dentalhub-v10.netlify.app;"

# Performance optimization for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"